package parade.player.controller;

import parade.card.Card;
import parade.computer.ComputerEngine;

/**
 * The ComputerController class is a representation of a computer player in the game. It relies on
 * the underlying IComputerEngine to determine the best moves for the player. The controller handles
 * the game state updates and player actions based on the server data received.
 *
 * <p>When prompted to play a card, the computer player will use its attached IComputerEngine
 * internal logic to decide which card to play. The controller will then send the chosen card back
 * to the game server.
 */
public class ComputerController extends AbstractPlayerController {
    private final ComputerEngine computerEngine;
    private static int index = 1;

    /**
     * Constructs a Computer player with a given name and the computer engine.
     *
     * @param name The name of the AI player.
     * @param computerEngine The computer engine to attach for the controller.
     */
    public ComputerController(String name, ComputerEngine computerEngine) {
        super(name);
        this.computerEngine = computerEngine;
    }

    /**
     * Constructors a Computer player with a computer engine.
     *
     * <p>Name is autogenerated based on the computer engine name and an auto-incremented index.
     *
     * @param computerEngine The computer engine to attach for the controller.
     */
    public ComputerController(ComputerEngine computerEngine) {
        this("Computer " + index++ + " [" + computerEngine.getName() + "]", computerEngine);
    }

    @Override
    public Card playCard(PlayCardData playCardData) {
        return computerEngine.process(
                player,
                playCardData.getOtherPlayers().stream()
                        .map(AbstractPlayerController::getPlayer)
                        .toList(),
                playCardData.getParade(),
                playCardData.getDeckSize());
    }

    @Override
    public Card discardCard(PlayCardData playCardData) {
        return computerEngine.discardCard(player, playCardData.getParade());
    }
}
